//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.0.0 (NJsonSchema v11.6.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class ApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    account(): Promise<AccountDto[]> {
        let url_ = this.baseUrl + "/api/Account";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAccount(_response);
        });
    }

    protected processAccount(response: Response): Promise<AccountDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(AccountDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AccountDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    emailLogin(body: EmailLoginRequest | undefined): Promise<LoginResponseDto> {
        let url_ = this.baseUrl + "/api/Authentication/email-login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processEmailLogin(_response);
        });
    }

    protected processEmailLogin(response: Response): Promise<LoginResponseDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = LoginResponseDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LoginResponseDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    generateLoginCode(body: GenerateLoginCodeRequest | undefined): Promise<GenerateLoginCodeResponseDto> {
        let url_ = this.baseUrl + "/api/Authentication/generate-login-code";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGenerateLoginCode(_response);
        });
    }

    protected processGenerateLoginCode(response: Response): Promise<GenerateLoginCodeResponseDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GenerateLoginCodeResponseDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GenerateLoginCodeResponseDto>(null as any);
    }

    /**
     * @return OK
     */
    callSettings(): Promise<CallSettingsDto> {
        let url_ = this.baseUrl + "/api/Call/CallSettings";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCallSettings(_response);
        });
    }

    protected processCallSettings(response: Response): Promise<CallSettingsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CallSettingsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CallSettingsDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    startOutgoingCall(body: StartOutgoingCallRequest | undefined): Promise<StartOutgoingCallDto> {
        let url_ = this.baseUrl + "/api/Call/StartOutgoingCall";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStartOutgoingCall(_response);
        });
    }

    protected processStartOutgoingCall(response: Response): Promise<StartOutgoingCallDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = StartOutgoingCallDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<StartOutgoingCallDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    handleIncomingCall(body: HandleIncomingCallRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Call/HandleIncomingCall";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHandleIncomingCall(_response);
        });
    }

    protected processHandleIncomingCall(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    logConnectionEstablished(body: LogConnectionEstablishedRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Call/LogConnectionEstablished";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogConnectionEstablished(_response);
        });
    }

    protected processLogConnectionEstablished(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    logRtcError(body: LogRtcErrorRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Call/LogRtcError";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogRtcError(_response);
        });
    }

    protected processLogRtcError(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    chatAll(): Promise<ChatDto[]> {
        let url_ = this.baseUrl + "/api/Chat";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChatAll(_response);
        });
    }

    protected processChatAll(response: Response): Promise<ChatDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ChatDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ChatDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    chat(body: CreateIndividualChatRequest | undefined): Promise<ChatDtoBase> {
        let url_ = this.baseUrl + "/api/Chat";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChat(_response);
        });
    }

    protected processChat(response: Response): Promise<ChatDtoBase> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ChatDtoBase.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ChatDtoBase>(null as any);
    }

    /**
     * @param page (optional) 
     * @return OK
     */
    messageAll(chatId: string, page: number | undefined): Promise<MessageDto[]> {
        let url_ = this.baseUrl + "/api/Message/{chatId}?";
        if (chatId === undefined || chatId === null)
            throw new globalThis.Error("The parameter 'chatId' must be defined.");
        url_ = url_.replace("{chatId}", encodeURIComponent("" + chatId));
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMessageAll(_response);
        });
    }

    protected processMessageAll(response: Response): Promise<MessageDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(MessageDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MessageDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    message(body: CreateMessageRequest | undefined): Promise<MessageDto> {
        let url_ = this.baseUrl + "/api/Message";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMessage(_response);
        });
    }

    protected processMessage(response: Response): Promise<MessageDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MessageDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MessageDto>(null as any);
    }

    /**
     * @param chatId (optional) 
     * @param messageId (optional) 
     * @return OK
     */
    markAsRead(chatId: string | undefined, messageId: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Message/MarkAsRead?";
        if (chatId === null)
            throw new globalThis.Error("The parameter 'chatId' cannot be null.");
        else if (chatId !== undefined)
            url_ += "chatId=" + encodeURIComponent("" + chatId) + "&";
        if (messageId === null)
            throw new globalThis.Error("The parameter 'messageId' cannot be null.");
        else if (messageId !== undefined)
            url_ += "messageId=" + encodeURIComponent("" + messageId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "PUT",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMarkAsRead(_response);
        });
    }

    protected processMarkAsRead(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    setLinkPreview(body: SetLinkPreviewRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Message/SetLinkPreview";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSetLinkPreview(_response);
        });
    }

    protected processSetLinkPreview(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    setImagePreview(body: SetImagePreviewRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Message/SetImagePreview";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSetImagePreview(_response);
        });
    }

    protected processSetImagePreview(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    profileGET(): Promise<ProfileDto> {
        let url_ = this.baseUrl + "/api/Profile";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProfileGET(_response);
        });
    }

    protected processProfileGET(response: Response): Promise<ProfileDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ProfileDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProfileDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    profilePUT(body: UpdateProfileRequest | undefined): Promise<ProfileDto> {
        let url_ = this.baseUrl + "/api/Profile";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProfilePUT(_response);
        });
    }

    protected processProfilePUT(response: Response): Promise<ProfileDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ProfileDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProfileDto>(null as any);
    }
}

export class AccountDto implements IAccountDto {
    id?: string | undefined;
    accountTypeId?: number;
    photoUrl?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    image?: ImageDto;

    constructor(data?: IAccountDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.accountTypeId = _data["accountTypeId"];
            this.photoUrl = _data["photoUrl"];
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.image = _data["image"] ? ImageDto.fromJS(_data["image"]) : undefined as any;
        }
    }

    static fromJS(data: any): AccountDto {
        data = typeof data === 'object' ? data : {};
        let result = new AccountDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["accountTypeId"] = this.accountTypeId;
        data["photoUrl"] = this.photoUrl;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["image"] = this.image ? this.image.toJSON() : undefined as any;
        return data;
    }
}

export interface IAccountDto {
    id?: string | undefined;
    accountTypeId?: number;
    photoUrl?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    image?: ImageDto;
}

export class CallSettingsDto implements ICallSettingsDto {
    iceServerConfiguration?: string | undefined;
    maxVideoDurationInSeconds?: number;

    constructor(data?: ICallSettingsDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.iceServerConfiguration = _data["iceServerConfiguration"];
            this.maxVideoDurationInSeconds = _data["maxVideoDurationInSeconds"];
        }
    }

    static fromJS(data: any): CallSettingsDto {
        data = typeof data === 'object' ? data : {};
        let result = new CallSettingsDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["iceServerConfiguration"] = this.iceServerConfiguration;
        data["maxVideoDurationInSeconds"] = this.maxVideoDurationInSeconds;
        return data;
    }
}

export interface ICallSettingsDto {
    iceServerConfiguration?: string | undefined;
    maxVideoDurationInSeconds?: number;
}

export class ChatDto implements IChatDto {
    id?: string | undefined;
    accountTypeId?: number;
    photoUrl?: string | undefined;
    chatName?: string | undefined;
    unreadCount?: number;
    lastMessageDate?: number;
    lastMessageId?: string | undefined;
    image?: ImageDto;
    isIndividual?: boolean;
    accountIds?: string[] | undefined;

    constructor(data?: IChatDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.accountTypeId = _data["accountTypeId"];
            this.photoUrl = _data["photoUrl"];
            this.chatName = _data["chatName"];
            this.unreadCount = _data["unreadCount"];
            this.lastMessageDate = _data["lastMessageDate"];
            this.lastMessageId = _data["lastMessageId"];
            this.image = _data["image"] ? ImageDto.fromJS(_data["image"]) : undefined as any;
            this.isIndividual = _data["isIndividual"];
            if (Array.isArray(_data["accountIds"])) {
                this.accountIds = [] as any;
                for (let item of _data["accountIds"])
                    this.accountIds!.push(item);
            }
        }
    }

    static fromJS(data: any): ChatDto {
        data = typeof data === 'object' ? data : {};
        let result = new ChatDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["accountTypeId"] = this.accountTypeId;
        data["photoUrl"] = this.photoUrl;
        data["chatName"] = this.chatName;
        data["unreadCount"] = this.unreadCount;
        data["lastMessageDate"] = this.lastMessageDate;
        data["lastMessageId"] = this.lastMessageId;
        data["image"] = this.image ? this.image.toJSON() : undefined as any;
        data["isIndividual"] = this.isIndividual;
        if (Array.isArray(this.accountIds)) {
            data["accountIds"] = [];
            for (let item of this.accountIds)
                data["accountIds"].push(item);
        }
        return data;
    }
}

export interface IChatDto {
    id?: string | undefined;
    accountTypeId?: number;
    photoUrl?: string | undefined;
    chatName?: string | undefined;
    unreadCount?: number;
    lastMessageDate?: number;
    lastMessageId?: string | undefined;
    image?: ImageDto;
    isIndividual?: boolean;
    accountIds?: string[] | undefined;
}

export class ChatDtoBase implements IChatDtoBase {
    id?: string | undefined;

    constructor(data?: IChatDtoBase) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): ChatDtoBase {
        data = typeof data === 'object' ? data : {};
        let result = new ChatDtoBase();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        return data;
    }
}

export interface IChatDtoBase {
    id?: string | undefined;
}

export class ConnectionDiagnostics implements IConnectionDiagnostics {
    connectionState?: string | undefined;
    localCandidateTypes?: string | undefined;
    remoteCandidateTypes?: string | undefined;
    browser?: string | undefined;
    platform?: string | undefined;

    constructor(data?: IConnectionDiagnostics) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.connectionState = _data["connectionState"];
            this.localCandidateTypes = _data["localCandidateTypes"];
            this.remoteCandidateTypes = _data["remoteCandidateTypes"];
            this.browser = _data["browser"];
            this.platform = _data["platform"];
        }
    }

    static fromJS(data: any): ConnectionDiagnostics {
        data = typeof data === 'object' ? data : {};
        let result = new ConnectionDiagnostics();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["connectionState"] = this.connectionState;
        data["localCandidateTypes"] = this.localCandidateTypes;
        data["remoteCandidateTypes"] = this.remoteCandidateTypes;
        data["browser"] = this.browser;
        data["platform"] = this.platform;
        return data;
    }
}

export interface IConnectionDiagnostics {
    connectionState?: string | undefined;
    localCandidateTypes?: string | undefined;
    remoteCandidateTypes?: string | undefined;
    browser?: string | undefined;
    platform?: string | undefined;
}

export class CreateIndividualChatRequest implements ICreateIndividualChatRequest {
    accountId?: string | undefined;

    constructor(data?: ICreateIndividualChatRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.accountId = _data["accountId"];
        }
    }

    static fromJS(data: any): CreateIndividualChatRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateIndividualChatRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["accountId"] = this.accountId;
        return data;
    }
}

export interface ICreateIndividualChatRequest {
    accountId?: string | undefined;
}

export class CreateMessageRequest implements ICreateMessageRequest {
    text?: string | undefined;
    chatId?: string | undefined;
    image?: ImageRequestModel;

    constructor(data?: ICreateMessageRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.text = _data["text"];
            this.chatId = _data["chatId"];
            this.image = _data["image"] ? ImageRequestModel.fromJS(_data["image"]) : undefined as any;
        }
    }

    static fromJS(data: any): CreateMessageRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateMessageRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text;
        data["chatId"] = this.chatId;
        data["image"] = this.image ? this.image.toJSON() : undefined as any;
        return data;
    }
}

export interface ICreateMessageRequest {
    text?: string | undefined;
    chatId?: string | undefined;
    image?: ImageRequestModel;
}

export class EmailLoginRequest implements IEmailLoginRequest {
    email?: string | undefined;
    code?: number;
    antiSpamToken?: number;

    constructor(data?: IEmailLoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.email = _data["email"];
            this.code = _data["code"];
            this.antiSpamToken = _data["antiSpamToken"];
        }
    }

    static fromJS(data: any): EmailLoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new EmailLoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["email"] = this.email;
        data["code"] = this.code;
        data["antiSpamToken"] = this.antiSpamToken;
        return data;
    }
}

export interface IEmailLoginRequest {
    email?: string | undefined;
    code?: number;
    antiSpamToken?: number;
}

export class GenerateLoginCodeRequest implements IGenerateLoginCodeRequest {
    email?: string | undefined;
    antiSpamToken?: number;

    constructor(data?: IGenerateLoginCodeRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.email = _data["email"];
            this.antiSpamToken = _data["antiSpamToken"];
        }
    }

    static fromJS(data: any): GenerateLoginCodeRequest {
        data = typeof data === 'object' ? data : {};
        let result = new GenerateLoginCodeRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["email"] = this.email;
        data["antiSpamToken"] = this.antiSpamToken;
        return data;
    }
}

export interface IGenerateLoginCodeRequest {
    email?: string | undefined;
    antiSpamToken?: number;
}

export class GenerateLoginCodeResponseDto implements IGenerateLoginCodeResponseDto {
    codeValidInSeconds?: number;

    constructor(data?: IGenerateLoginCodeResponseDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.codeValidInSeconds = _data["codeValidInSeconds"];
        }
    }

    static fromJS(data: any): GenerateLoginCodeResponseDto {
        data = typeof data === 'object' ? data : {};
        let result = new GenerateLoginCodeResponseDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["codeValidInSeconds"] = this.codeValidInSeconds;
        return data;
    }
}

export interface IGenerateLoginCodeResponseDto {
    codeValidInSeconds?: number;
}

export class HandleIncomingCallRequest implements IHandleIncomingCallRequest {
    callId?: string | undefined;
    chatId?: string | undefined;
    answer?: string | undefined;
    connectionDiagnostics?: ConnectionDiagnostics;
    iceGatheringElapsedMs?: number;
    iceGatheringCollectedAll?: boolean;

    constructor(data?: IHandleIncomingCallRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.callId = _data["callId"];
            this.chatId = _data["chatId"];
            this.answer = _data["answer"];
            this.connectionDiagnostics = _data["connectionDiagnostics"] ? ConnectionDiagnostics.fromJS(_data["connectionDiagnostics"]) : undefined as any;
            this.iceGatheringElapsedMs = _data["iceGatheringElapsedMs"];
            this.iceGatheringCollectedAll = _data["iceGatheringCollectedAll"];
        }
    }

    static fromJS(data: any): HandleIncomingCallRequest {
        data = typeof data === 'object' ? data : {};
        let result = new HandleIncomingCallRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["callId"] = this.callId;
        data["chatId"] = this.chatId;
        data["answer"] = this.answer;
        data["connectionDiagnostics"] = this.connectionDiagnostics ? this.connectionDiagnostics.toJSON() : undefined as any;
        data["iceGatheringElapsedMs"] = this.iceGatheringElapsedMs;
        data["iceGatheringCollectedAll"] = this.iceGatheringCollectedAll;
        return data;
    }
}

export interface IHandleIncomingCallRequest {
    callId?: string | undefined;
    chatId?: string | undefined;
    answer?: string | undefined;
    connectionDiagnostics?: ConnectionDiagnostics;
    iceGatheringElapsedMs?: number;
    iceGatheringCollectedAll?: boolean;
}

export class ImageDto implements IImageDto {
    id?: string | undefined;
    fileStorageTypeId?: number;

    constructor(data?: IImageDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.fileStorageTypeId = _data["fileStorageTypeId"];
        }
    }

    static fromJS(data: any): ImageDto {
        data = typeof data === 'object' ? data : {};
        let result = new ImageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["fileStorageTypeId"] = this.fileStorageTypeId;
        return data;
    }
}

export interface IImageDto {
    id?: string | undefined;
    fileStorageTypeId?: number;
}

export class ImagePreviewDto implements IImagePreviewDto {
    messageId?: string | undefined;
    id?: string | undefined;
    chatId?: string | undefined;
    width?: number | undefined;
    height?: number | undefined;
    fileStorageTypeId?: number;

    constructor(data?: IImagePreviewDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.messageId = _data["messageId"];
            this.id = _data["id"];
            this.chatId = _data["chatId"];
            this.width = _data["width"];
            this.height = _data["height"];
            this.fileStorageTypeId = _data["fileStorageTypeId"];
        }
    }

    static fromJS(data: any): ImagePreviewDto {
        data = typeof data === 'object' ? data : {};
        let result = new ImagePreviewDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["messageId"] = this.messageId;
        data["id"] = this.id;
        data["chatId"] = this.chatId;
        data["width"] = this.width;
        data["height"] = this.height;
        data["fileStorageTypeId"] = this.fileStorageTypeId;
        return data;
    }
}

export interface IImagePreviewDto {
    messageId?: string | undefined;
    id?: string | undefined;
    chatId?: string | undefined;
    width?: number | undefined;
    height?: number | undefined;
    fileStorageTypeId?: number;
}

export class ImageRequestModel implements IImageRequestModel {
    id?: string | undefined;
    width?: number;
    height?: number;
    imageFormat?: number;
    fileStorageTypeId?: number;
    signature?: string | undefined;

    constructor(data?: IImageRequestModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.width = _data["width"];
            this.height = _data["height"];
            this.imageFormat = _data["imageFormat"];
            this.fileStorageTypeId = _data["fileStorageTypeId"];
            this.signature = _data["signature"];
        }
    }

    static fromJS(data: any): ImageRequestModel {
        data = typeof data === 'object' ? data : {};
        let result = new ImageRequestModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["width"] = this.width;
        data["height"] = this.height;
        data["imageFormat"] = this.imageFormat;
        data["fileStorageTypeId"] = this.fileStorageTypeId;
        data["signature"] = this.signature;
        return data;
    }
}

export interface IImageRequestModel {
    id?: string | undefined;
    width?: number;
    height?: number;
    imageFormat?: number;
    fileStorageTypeId?: number;
    signature?: string | undefined;
}

export class LinkPreviewDto implements ILinkPreviewDto {
    messageId?: string | undefined;
    chatId?: string | undefined;
    title?: string | undefined;
    imageUrl?: string | undefined;
    url?: string | undefined;

    constructor(data?: ILinkPreviewDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.messageId = _data["messageId"];
            this.chatId = _data["chatId"];
            this.title = _data["title"];
            this.imageUrl = _data["imageUrl"];
            this.url = _data["url"];
        }
    }

    static fromJS(data: any): LinkPreviewDto {
        data = typeof data === 'object' ? data : {};
        let result = new LinkPreviewDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["messageId"] = this.messageId;
        data["chatId"] = this.chatId;
        data["title"] = this.title;
        data["imageUrl"] = this.imageUrl;
        data["url"] = this.url;
        return data;
    }
}

export interface ILinkPreviewDto {
    messageId?: string | undefined;
    chatId?: string | undefined;
    title?: string | undefined;
    imageUrl?: string | undefined;
    url?: string | undefined;
}

export class LogConnectionEstablishedRequest implements ILogConnectionEstablishedRequest {
    callId?: string | undefined;
    chatId?: string | undefined;
    connectionDiagnostics?: ConnectionDiagnostics;

    constructor(data?: ILogConnectionEstablishedRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.callId = _data["callId"];
            this.chatId = _data["chatId"];
            this.connectionDiagnostics = _data["connectionDiagnostics"] ? ConnectionDiagnostics.fromJS(_data["connectionDiagnostics"]) : undefined as any;
        }
    }

    static fromJS(data: any): LogConnectionEstablishedRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LogConnectionEstablishedRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["callId"] = this.callId;
        data["chatId"] = this.chatId;
        data["connectionDiagnostics"] = this.connectionDiagnostics ? this.connectionDiagnostics.toJSON() : undefined as any;
        return data;
    }
}

export interface ILogConnectionEstablishedRequest {
    callId?: string | undefined;
    chatId?: string | undefined;
    connectionDiagnostics?: ConnectionDiagnostics;
}

export class LogRtcErrorRequest implements ILogRtcErrorRequest {
    callId?: string | undefined;
    chatId?: string | undefined;
    connectionDiagnostics?: ConnectionDiagnostics;
    errorType?: RtcErrorType;
    error?: string | undefined;
    errorMessage?: string | undefined;
    stackTrace?: string | undefined;

    constructor(data?: ILogRtcErrorRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.callId = _data["callId"];
            this.chatId = _data["chatId"];
            this.connectionDiagnostics = _data["connectionDiagnostics"] ? ConnectionDiagnostics.fromJS(_data["connectionDiagnostics"]) : undefined as any;
            this.errorType = _data["errorType"];
            this.error = _data["error"];
            this.errorMessage = _data["errorMessage"];
            this.stackTrace = _data["stackTrace"];
        }
    }

    static fromJS(data: any): LogRtcErrorRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LogRtcErrorRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["callId"] = this.callId;
        data["chatId"] = this.chatId;
        data["connectionDiagnostics"] = this.connectionDiagnostics ? this.connectionDiagnostics.toJSON() : undefined as any;
        data["errorType"] = this.errorType;
        data["error"] = this.error;
        data["errorMessage"] = this.errorMessage;
        data["stackTrace"] = this.stackTrace;
        return data;
    }
}

export interface ILogRtcErrorRequest {
    callId?: string | undefined;
    chatId?: string | undefined;
    connectionDiagnostics?: ConnectionDiagnostics;
    errorType?: RtcErrorType;
    error?: string | undefined;
    errorMessage?: string | undefined;
    stackTrace?: string | undefined;
}

export class LoginResponseDto implements ILoginResponseDto {
    success?: boolean;
    token?: string | undefined;

    constructor(data?: ILoginResponseDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.token = _data["token"];
        }
    }

    static fromJS(data: any): LoginResponseDto {
        data = typeof data === 'object' ? data : {};
        let result = new LoginResponseDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["token"] = this.token;
        return data;
    }
}

export interface ILoginResponseDto {
    success?: boolean;
    token?: string | undefined;
}

export class MessageDto implements IMessageDto {
    id?: string | undefined;
    text?: string | undefined;
    textHtml?: string | undefined;
    chatId?: string | undefined;
    isMine?: boolean | undefined;
    created?: number;
    linkPreview?: LinkPreviewDto;
    image?: ImageDto;
    imagePreview?: ImagePreviewDto;
    emojisOnly?: boolean;
    emojiCount?: number;

    constructor(data?: IMessageDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.text = _data["text"];
            this.textHtml = _data["textHtml"];
            this.chatId = _data["chatId"];
            this.isMine = _data["isMine"];
            this.created = _data["created"];
            this.linkPreview = _data["linkPreview"] ? LinkPreviewDto.fromJS(_data["linkPreview"]) : undefined as any;
            this.image = _data["image"] ? ImageDto.fromJS(_data["image"]) : undefined as any;
            this.imagePreview = _data["imagePreview"] ? ImagePreviewDto.fromJS(_data["imagePreview"]) : undefined as any;
            this.emojisOnly = _data["emojisOnly"];
            this.emojiCount = _data["emojiCount"];
        }
    }

    static fromJS(data: any): MessageDto {
        data = typeof data === 'object' ? data : {};
        let result = new MessageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["text"] = this.text;
        data["textHtml"] = this.textHtml;
        data["chatId"] = this.chatId;
        data["isMine"] = this.isMine;
        data["created"] = this.created;
        data["linkPreview"] = this.linkPreview ? this.linkPreview.toJSON() : undefined as any;
        data["image"] = this.image ? this.image.toJSON() : undefined as any;
        data["imagePreview"] = this.imagePreview ? this.imagePreview.toJSON() : undefined as any;
        data["emojisOnly"] = this.emojisOnly;
        data["emojiCount"] = this.emojiCount;
        return data;
    }
}

export interface IMessageDto {
    id?: string | undefined;
    text?: string | undefined;
    textHtml?: string | undefined;
    chatId?: string | undefined;
    isMine?: boolean | undefined;
    created?: number;
    linkPreview?: LinkPreviewDto;
    image?: ImageDto;
    imagePreview?: ImagePreviewDto;
    emojisOnly?: boolean;
    emojiCount?: number;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class ProfileDto implements IProfileDto {
    id?: string | undefined;
    photoUrl?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    email?: string | undefined;
    image?: ImageDto;

    constructor(data?: IProfileDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.photoUrl = _data["photoUrl"];
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.email = _data["email"];
            this.image = _data["image"] ? ImageDto.fromJS(_data["image"]) : undefined as any;
        }
    }

    static fromJS(data: any): ProfileDto {
        data = typeof data === 'object' ? data : {};
        let result = new ProfileDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["photoUrl"] = this.photoUrl;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["email"] = this.email;
        data["image"] = this.image ? this.image.toJSON() : undefined as any;
        return data;
    }
}

export interface IProfileDto {
    id?: string | undefined;
    photoUrl?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    email?: string | undefined;
    image?: ImageDto;
}

export enum RtcErrorType {
    NotSet = "NotSet",
    Connection = "Connection",
    IceServer = "IceServer",
    Media = "Media",
}

export class SetImagePreviewRequest implements ISetImagePreviewRequest {
    messageId?: string | undefined;
    chatId?: string | undefined;
    filename?: string | undefined;
    imageFormat?: number;
    width?: number;
    height?: number;
    fileStorageTypeId?: number;
    signature?: string | undefined;

    constructor(data?: ISetImagePreviewRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.messageId = _data["messageId"];
            this.chatId = _data["chatId"];
            this.filename = _data["filename"];
            this.imageFormat = _data["imageFormat"];
            this.width = _data["width"];
            this.height = _data["height"];
            this.fileStorageTypeId = _data["fileStorageTypeId"];
            this.signature = _data["signature"];
        }
    }

    static fromJS(data: any): SetImagePreviewRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SetImagePreviewRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["messageId"] = this.messageId;
        data["chatId"] = this.chatId;
        data["filename"] = this.filename;
        data["imageFormat"] = this.imageFormat;
        data["width"] = this.width;
        data["height"] = this.height;
        data["fileStorageTypeId"] = this.fileStorageTypeId;
        data["signature"] = this.signature;
        return data;
    }
}

export interface ISetImagePreviewRequest {
    messageId?: string | undefined;
    chatId?: string | undefined;
    filename?: string | undefined;
    imageFormat?: number;
    width?: number;
    height?: number;
    fileStorageTypeId?: number;
    signature?: string | undefined;
}

export class SetLinkPreviewRequest implements ISetLinkPreviewRequest {
    messageId?: string | undefined;
    chatId?: string | undefined;
    url?: string | undefined;
    title?: string | undefined;
    imageUrl?: string | undefined;
    signature?: string | undefined;

    constructor(data?: ISetLinkPreviewRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.messageId = _data["messageId"];
            this.chatId = _data["chatId"];
            this.url = _data["url"];
            this.title = _data["title"];
            this.imageUrl = _data["imageUrl"];
            this.signature = _data["signature"];
        }
    }

    static fromJS(data: any): SetLinkPreviewRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SetLinkPreviewRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["messageId"] = this.messageId;
        data["chatId"] = this.chatId;
        data["url"] = this.url;
        data["title"] = this.title;
        data["imageUrl"] = this.imageUrl;
        data["signature"] = this.signature;
        return data;
    }
}

export interface ISetLinkPreviewRequest {
    messageId?: string | undefined;
    chatId?: string | undefined;
    url?: string | undefined;
    title?: string | undefined;
    imageUrl?: string | undefined;
    signature?: string | undefined;
}

export class StartOutgoingCallDto implements IStartOutgoingCallDto {
    callId!: string;

    constructor(data?: IStartOutgoingCallDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.callId = _data["callId"];
        }
    }

    static fromJS(data: any): StartOutgoingCallDto {
        data = typeof data === 'object' ? data : {};
        let result = new StartOutgoingCallDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["callId"] = this.callId;
        return data;
    }
}

export interface IStartOutgoingCallDto {
    callId: string;
}

export class StartOutgoingCallRequest implements IStartOutgoingCallRequest {
    callId?: string | undefined;
    chatId?: string | undefined;
    offer?: string | undefined;
    connectionDiagnostics?: ConnectionDiagnostics;
    iceGatheringElapsedMs?: number;
    iceGatheringCollectedAll?: boolean;

    constructor(data?: IStartOutgoingCallRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.callId = _data["callId"];
            this.chatId = _data["chatId"];
            this.offer = _data["offer"];
            this.connectionDiagnostics = _data["connectionDiagnostics"] ? ConnectionDiagnostics.fromJS(_data["connectionDiagnostics"]) : undefined as any;
            this.iceGatheringElapsedMs = _data["iceGatheringElapsedMs"];
            this.iceGatheringCollectedAll = _data["iceGatheringCollectedAll"];
        }
    }

    static fromJS(data: any): StartOutgoingCallRequest {
        data = typeof data === 'object' ? data : {};
        let result = new StartOutgoingCallRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["callId"] = this.callId;
        data["chatId"] = this.chatId;
        data["offer"] = this.offer;
        data["connectionDiagnostics"] = this.connectionDiagnostics ? this.connectionDiagnostics.toJSON() : undefined as any;
        data["iceGatheringElapsedMs"] = this.iceGatheringElapsedMs;
        data["iceGatheringCollectedAll"] = this.iceGatheringCollectedAll;
        return data;
    }
}

export interface IStartOutgoingCallRequest {
    callId?: string | undefined;
    chatId?: string | undefined;
    offer?: string | undefined;
    connectionDiagnostics?: ConnectionDiagnostics;
    iceGatheringElapsedMs?: number;
    iceGatheringCollectedAll?: boolean;
}

export class UpdateProfileRequest implements IUpdateProfileRequest {
    firstName?: string | undefined;
    lastName?: string | undefined;
    image?: ImageRequestModel;

    constructor(data?: IUpdateProfileRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.image = _data["image"] ? ImageRequestModel.fromJS(_data["image"]) : undefined as any;
        }
    }

    static fromJS(data: any): UpdateProfileRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateProfileRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["image"] = this.image ? this.image.toJSON() : undefined as any;
        return data;
    }
}

export interface IUpdateProfileRequest {
    firstName?: string | undefined;
    lastName?: string | undefined;
    image?: ImageRequestModel;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}