<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.62.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\Configuration\LetsTalk.Server.Configuration\LetsTalk.Server.Configuration.csproj" />
    <ProjectReference Include="..\..\..\Shared\LetsTalk.Server.DateHelpers\LetsTalk.Server.DateHelpers.csproj" />
    <ProjectReference Include="..\LetsTalk.Server.Persistence.CosmosDB.Repository.Abstractions\LetsTalk.Server.Persistence.CosmosDB.Repository.Abstractions.csproj" />
  </ItemGroup>

</Project>
